"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const UserController_1 = require("../controllers/UserController");
const router = (0, express_1.Router)();
const userController = new UserController_1.UserController();
router.get("/", userController.findAll);
router.get("/:id", userController.findById);
router.post("/", userController.create);
router.put("/:id", userController.update);
router.delete("/:id", userController.delete);
exports.default = router;
